// Generated by CoffeeScript 1.6.3
(function() {
  exports.test1 = function() {
    throw new Error('test 1');
  };

  exports.test2 = function() {
    throw new Error('test 2');
  };

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
